# Dockerfile.prod

# build environment
FROM node:17.1-alpine as build-stage
WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH
COPY package*.json ./
COPY . .
RUN npm run build

# production environment
FROM nginx:stable-alpine as prod-stage
COPY --from=build-stage /app/build /usr/share/nginx/html
# to make react-router work with nginx
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
